version: '3.8'
services:
  backend:
    image: ghcr.io/bezidev/sharepoint-bot
    volumes:
      - ./config.json:/app/config.json
      - ./database:/app/database
    environment:
      - TZ=Europe/Ljubljana
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
