name: Server
on:
  - push

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Get Docker version
        run: docker --version
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: "ghcr.io"
      - name: Downcase repository owner
        run: |
          echo REPO=$(echo ${{github.repository_owner}} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: "."
          file: "./Dockerfile"
          tags: ghcr.io/${{env.REPO}}/sharepoint-bot:latest
          push: true
